[package]
name = "russ"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
cosmic-text = "0.12.1"
image = "0.25.2"
softbuffer = "0.4.5"
swash = "0.1.18"
tiny-skia = "0.11.4"
winit = "0.30.5"
